# Generated by Django 4.2.7 on 2023-11-09 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Название категории, например, 'Недвижимость' или 'Транспорт'", max_length=100, unique=True, verbose_name='Названия')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания этой категории', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение, связанное с объявлением', upload_to='ads_images/', verbose_name='Изображение')),
                ('title', models.CharField(help_text="Заголовок объявления, например, 'Продам ноутбук ASUS XPS'", max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Подробное описание объявления, включая характеристики и детали', max_length=999, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text="Цена товара или услуги, например, '1500.00'", max_digits=15, verbose_name='Цена')),
                ('contact', models.CharField(help_text='Контактный телефон для связи с автором объявления', max_length=100, verbose_name='Телефон для связи')),
                ('address', models.CharField(blank=True, help_text='Физический адрес, если применимо', max_length=255, null=True, verbose_name='Адрес')),
                ('whatsapp', models.URLField(blank=True, help_text='Ссылка на WhatsApp для связи с автором объявления', null=True, verbose_name='Ссылка на whatsapp')),
                ('telegram', models.URLField(blank=True, help_text='Ссылка на Telegram для связи с автором объявления', null=True, verbose_name='Ссылка на telegram')),
                ('instagram', models.URLField(blank=True, help_text='Ссылка на Instagram для связи с автором объявления', null=True, verbose_name='Ссылка на instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания объявления', verbose_name='Дата создания')),
                ('category', models.ForeignKey(help_text='Категория, к которой принадлежит объявление', on_delete=django.db.models.deletion.CASCADE, to='ads.category', verbose_name='Категория')),
                ('user', models.ForeignKey(help_text='Пользователь, который разместил объявление', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
